version: '3.8'

services:
  database:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: stuff
      POSTGRES_HOST: localhost
    ports:
      - '5000:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: